apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
data:
  Jwt__Issuer: "FiapCloudGames.UsersApi"
  Jwt__Audience: "FiapCloudGames"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
  ASPNETCORE_URLS: "http://+:8080"
